creation_rules:
- path_regex: \.(yml|yaml)
  encrypted_regex: "(^(.*[Pp]ass.*)$)|(^(data|stringData)$)"
    #age: age1k8mxus4jftcnd5jerd5cq7jwhc07kyztp0mcwrts60l6j9dd04rs767ua2
  azure_keyvault: "https://kv-prod-usc-sops.vault.azure.net/keys/sops-key/907d3cff614f417dbb7fdd889b81e5e5"


