apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
spec:
    interval: 5m
    chart:
        spec:
            version: 45.x
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
            interval: 60m
    install:
        crds: Create
    upgrade:
        crds: CreateReplace
    # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
    values:
        alertmanager:
            enabled: true
        prometheus:
            prometheusSpec:
                retention: 24h
                resources:
                    requests:
                        cpu: 200m
                        memory: 200Mi
                podMonitorNamespaceSelector: {}
                podMonitorSelector:
                    matchLabels:
                        app.kubernetes.io/component: monitoring
        grafana:
            adminPassword: ENC[AES256_GCM,data:7wcIEvYx1ZPvgvgbjNtXd7FVDEOyK7EVT4+hA5jMtvWjWbSMNHIBZyO/S1OQm2NRdB0p,iv:rP4hF8qwaSZpjymTN9Hnf/6xOUvzx+kuvpq5BhObkxU=,tag:kYyzLDtvARSFvRF82QqSVw==,type:str]
    postRenderers:
        - kustomize:
            patches:
                - target:
                    # Ignore these objects from Flux diff as they are mutated from chart hooks
                    kind: (ValidatingWebhookConfiguration|MutatingWebhookConfiguration)
                    name: kube-prometheus-stack-admission
                  patch: |
                    - op: add
                      path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                      value: disabled
                - target:
                    # Ignore these objects from Flux diff as they are mutated at apply time but not at dry-run time
                    kind: PrometheusRule
                  patch: |-
                    - op: add
                      path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                      value: disabled
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qcyqkv37ymke7amppcr2l5leerq8nhr0z7g64tw0ngw8qurkza8qxgrems
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL3dtTEEyZWdoZllwOTQ5
            Z3pWSkh1c2xpKzUvR1RCQThzb1BmZzd2TEY4CjVHdVU2MzloT1gzYzJnOXZSNjlZ
            eWNscDdKQ21FSmdwQkVyUTFDRWdLVGcKLS0tIDZwV2NvRkVSU1Z5SFI3RzlMY1ZD
            ZnFKdmltVS9nWlg2NUZ3VkhkVmFwUlkKkP5VqYb4man/XxBCKXE5R4JLxdIKhyaB
            JtQi4cgC9QIK6R069ti0ZdSASEbMBctHhm4nk3J1D53AZMd1Haq4Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T19:24:34Z"
    mac: ENC[AES256_GCM,data:zaqC44gcciks4RuV0dyPKs7SEu1gxY8WtQSpK8uX5p2X3IRMcF6hZMwA9b2ZK/s3hSMrN5NXKFHEyfNaIPBW1HjI7q/gfRZHVJrR7BbHDpqS7BqEvKiabNWZATL+ZlJFdF0oenO7Vwv9VixoYcpyQqsXUmJRylf+9jsl4bN6sbM=,iv:q8ZfbmSoh7Oyz7d2kxjxpMV2XS2J+PdVAr4xKPSKpeI=,tag:qhKcdIu4BsO2vwscRGpkcQ==,type:str]
    pgp: []
    encrypted_regex: (^(.*[Pp]ass.*)$)|(^(data|stringData)$)|(^(.*[Tt]oken.*)$)
    version: 3.7.3
