apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ec1IHguYc7h+W2si4kBIt/f1CNGf5+STl2hgfixCQ0iTI8IybDbB5g==,iv:sv/cSp/+/PdDl6uCKuViyNmj75BM+WG/4aNRFjJLOAo=,tag:Lqy31wRVoeJtzBOzy2MnYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qcyqkv37ymke7amppcr2l5leerq8nhr0z7g64tw0ngw8qurkza8qxgrems
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOG9aN1FqWGxKeDNkR0hY
            WXdwaUdCUEl5OTNKWm83T21xb2M2SlJOL0d3Ci9nemhvVFcvdEJnTHlWSGhhczlx
            QXg1Y3d2V2ZIZWJmcHZwT2FEcEN4azgKLS0tIHl0aUhqYnRISkNiVWJZcWRTRXpH
            amU1TytsUndkVi8xVlRDRXB6ekQ5WGMKDV2OsPTI34j04k1w9g6BTtHdwItoqeEt
            dw+iyginhpicXIZjw7YQWVQ1ND+ET4TZ05bFzkAp7/CNG19GoCbPtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T17:40:31Z"
    mac: ENC[AES256_GCM,data:6BC/kIlwCitzh7rUaEEWlTlJ0IFPbkzeHazZfeyP4G9GAZWopFtflRQ9lFGFAplko/7/A5AteG9r6ACpMt4IuCBLjpqHAkZ0TDgs2GJorH9u9exvphkTWwxL5Zb258xlYyAu/C/2jpTG8+ES13ZREj0IH1Qmqi/XHDW3UzjmX7Y=,iv:BVZ/8ABn6nRQ9SxmtfkWUvw2MLwMlluBNACldQblhi4=,tag:wnnaRt97ScWSnmhEbNeo+A==,type:str]
    pgp: []
    encrypted_regex: (^(.*[Pp]ass.*)$)|(^(data|stringData)$)|(^(.*[Tt]oken.*)$)
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: traefik-system
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ec1IHguYc7h+W2si4kBIt/f1CNGf5+STl2hgfixCQ0iTI8IybDbB5g==,iv:sv/cSp/+/PdDl6uCKuViyNmj75BM+WG/4aNRFjJLOAo=,tag:Lqy31wRVoeJtzBOzy2MnYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qcyqkv37ymke7amppcr2l5leerq8nhr0z7g64tw0ngw8qurkza8qxgrems
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOG9aN1FqWGxKeDNkR0hY
            WXdwaUdCUEl5OTNKWm83T21xb2M2SlJOL0d3Ci9nemhvVFcvdEJnTHlWSGhhczlx
            QXg1Y3d2V2ZIZWJmcHZwT2FEcEN4azgKLS0tIHl0aUhqYnRISkNiVWJZcWRTRXpH
            amU1TytsUndkVi8xVlRDRXB6ekQ5WGMKDV2OsPTI34j04k1w9g6BTtHdwItoqeEt
            dw+iyginhpicXIZjw7YQWVQ1ND+ET4TZ05bFzkAp7/CNG19GoCbPtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T17:40:31Z"
    mac: ENC[AES256_GCM,data:6BC/kIlwCitzh7rUaEEWlTlJ0IFPbkzeHazZfeyP4G9GAZWopFtflRQ9lFGFAplko/7/A5AteG9r6ACpMt4IuCBLjpqHAkZ0TDgs2GJorH9u9exvphkTWwxL5Zb258xlYyAu/C/2jpTG8+ES13ZREj0IH1Qmqi/XHDW3UzjmX7Y=,iv:BVZ/8ABn6nRQ9SxmtfkWUvw2MLwMlluBNACldQblhi4=,tag:wnnaRt97ScWSnmhEbNeo+A==,type:str]
    pgp: []
    encrypted_regex: (^(.*[Pp]ass.*)$)|(^(data|stringData)$)|(^(.*[Tt]oken.*)$)
    version: 3.7.3
