apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:fhP0uK4IaSiDdOl7Qjlkeg7N5fA7jfJFR5MJfKbrQOTixZQfFw/VFpq8k6S0L4yNutI4nses870=,iv:zTRgvl5o9BJtiKMy/N9JBU5DpSQ3imY4/dpe7iOgeu4=,tag:lIIkQhy36aL+UeYvP/i/qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qcyqkv37ymke7amppcr2l5leerq8nhr0z7g64tw0ngw8qurkza8qxgrems
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cjF5OFZJMzVGYVB6cnA1
            RGNPQ29yMjQ3aUhjeS9WSlFBUnJZUlJ1aGlrCmdtYzBwWkRDNmIzQmFWcXp6cm92
            QjdmemFSRjZqV2cvVm9QRUZVTURUYVUKLS0tIFdBSVU3RHZpWTgybUJxdkExOFRG
            Zk1qQyszTlNEeEV1S0JXbk9qQzhBZmMKyx6skXbLxXoXBZgEDbLiuk+/6KdqpIOj
            A0pj8GoAJwQPz+c35/16642vum92zowAyPoSpLke6qeD/K0EVQF+lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T17:46:30Z"
    mac: ENC[AES256_GCM,data:pNWb9E7f2D3iXlx2Ev0gAexPEBX8xmSmfn0k2EeyjWvKK0A8+BUrhx6utilJzqF60+Bul3lrmP8h+uX/AH9EAhBsoSxhbu8EpDWWMDES+0GiVrBrBleRy4oQeuf6uJFMJXRKIzADzbpNnFyVAhsJONG2vv3GgMsVhfMPho7jZZw=,iv:AA+1LcdswDHywgcZh2nGDo3eBEpHpN6KZTnaxvB5lsc=,tag:MYH7Q0XRwu8SfLNaQia5Gw==,type:str]
    pgp: []
    encrypted_regex: (^(.*[Pp]ass.*)$)|(^(data|stringData)$)|(^(.*[Tt]oken.*)$)
    version: 3.7.3
