apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: groundcover
    namespace: groundcover
spec:
    releaseName: groundcover
    chart:
        spec:
            chart: groundcover
            sourceRef:
                kind: HelmRepository
                name: groundcover
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        global:
            groundcover_token: ENC[AES256_GCM,data:sG12Ssm6VFOSzxj+VH/62Ue5cpGaVV0WEdFcHTsso8A7CMr50WZ2CXzNFBfwzJbq8+WiEL5QIdvSpaMgJeKrVlDAgXlOp615+bxFSxcF+cl3l/M0xEMnNrT+wyQ7kNgIKWVo1XH2GHo1i7xhUSEZa96hg3EsYzg37eVImidBgy9CssRV6Pi32Kv+EC/fdY4vWQq1Fp5TODg7NnIJQLg4MEkC2lUXTIqQKZc6PSLDN+6nHiqur1qST4B4NL2p7UyAevDDV9d9etkJFzMr84sDeB8ZqMKFAKbnVyHg3oZSxGmyQ7X7ZtNZs5w4Vfl0vei1B7xrqP4ca07djvn0qLzvBCg26vImt9U7XcJ185/Yd5YMYcNQIqLFkA==,iv:5ol4mcsyXUVP1Jf4duXSb+FXShv3/XmlRovNOWl+SUE=,tag:Y1Jw8TJG5x83XrArv70S+w==,type:str]
        timescaledb-single:
            secrets:
                credentials:
                    PATRONI_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:bR5ESvCN2dheeH/GFYhfN8nrIa8dYRwtVNdP7vGM0NpVDl6eM04ww/Ks256n3gSlKctzJCbuxlWLkdvt+8Bh9ff2eCQ=,iv:o9MFLZF2i6V/LvNn+DGMbiMCtDUpf+YbrT0SANh0ZvM=,tag:DQc1S15xJUZko++HPpFt1Q==,type:str]
                    PATRONI_REPLICATION_PASSWORD: ENC[AES256_GCM,data:yR7ICYjuqF12TBr8fltB4R/An0ziwCUBahvzy7465nma+3Sx1CF9BU2X2UDm7J9TqdKfOi+sB4q4sJ9VL8tQ1a8I/5g=,iv:OzIk1Te0KJCPvPxSeLAVqvBs+vu7gNcZ34aqqqwDZ7c=,tag:TedZ8cgX8YkUOMzJOC1raw==,type:str]
                    PATRONI_admin_PASSWORD: ENC[AES256_GCM,data:y+KEDVBsERsSZmovQxzyO+dtu5qAFemErIhFp9UZdUzqa22o3Q1TQ9xZAqL4V68p5jr9RTqvCLHAYA+gwtbRteglPfg=,iv:j5YVpIAxXjP+lWBjLo8jaTFcwGH6fOfFpnyC4r1SS3w=,tag:aQ31xYYt57Kh9z5TNggF9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qcyqkv37ymke7amppcr2l5leerq8nhr0z7g64tw0ngw8qurkza8qxgrems
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNWg2MDVRNFE2alNJNkRM
            dTVhMzh5bXFLUC9acW4zZVV2SXp3VjZCZ21zCkI5bENMSHcwb1AyTG15WGZhZUFP
            YUFuN0lsSmlHbElabC96bTY5ckZRTk0KLS0tIHlubGVtczl0Y0poT3FLMHUvcURB
            L3hyVTJZcjMvdURHcUlKbGFFdGYxYm8KPAntg6HkF7Av12ogWYnu9IT58gXiBRBc
            cDKAbuIBxXUUpH8Sa0EaJMN5YNegWmQjCKbiuY/OlY8hGoFtgR+xIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T19:44:02Z"
    mac: ENC[AES256_GCM,data:WKCta17LJUYSZm0ZnQ9GqQTeBVJBa1c+VOd3eqatMjkGTVdoK2Jlsk4xmpQKaiu0Bl7ih6ltrnLZ6QrcswM7ZT52E54aCq5mV9saAhPetF73aLJfu/vU0eGZzt6VlkD+7sTjfAzhTeqEpHP4lAkn//FXi/ippKAtMjWOI6cOZKg=,iv:S4S27FC5C/741lMKFL7T9qhH12wUJirxc+W22rQaTYk=,tag:FfWzotra4FhhaEZEkox5Ug==,type:str]
    pgp: []
    encrypted_regex: (^(.*[Pp]ass.*)$)|(^(data|stringData)$)|(^(.*[Tt]oken.*)$)|(^(.*[Kk]ey.*)$)|(^(.*PASSWORD.*)$)
    version: 3.7.3
