apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: groundcover
    namespace: groundcover
spec:
    releaseName: groundcover
    chart:
        spec:
            chart: groundcover
            sourceRef:
                kind: HelmRepository
                name: groundcover
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        global:
            groundcover_token: ENC[AES256_GCM,data:Dcdhs/5LnllklaRh9ZnpU/seF8Q435HsCZ17f7h/YaDC1QTRaCbOPRuBVW48WjwBG884VN9vWMZyskUGS1nxhPF1oqfe1Xjnj9VxbHXHbetU4I47S03dJ3tRpbcScLOevr6We6+g4xdtWJZnf/2WtGz9mHJAq8EWlGfyvd2RLWOIUQcbVkK3OqlLaUhJ5H/hf06E+1g2pLxy+tZFVuowHgsxLdWYopdmv8QB/no2ZbIJhKAvOA9shhjHlBTe9RnCTPESAkCsvFPMNYEuzn4FR16mY5WtRmNxOSqj4ev4tTU4m8BpghHX7M0Qcqskv/+myQI1hvLUXS3juRHV8yyd4coBBPtC142odkcUoAcFi+zGRNMmxDG0cg==,iv:PW4MBP56lo+GjaSsBXYAzUDBZM+XYLKPbfL/dbk3Yds=,tag:pWTkPhNzkn9fJEV3GoOJjg==,type:str]
        clusterId: talos-tfinklea
        timescaledb-single:
            secrets:
                credentials:
                    PATRONI_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:7g/L11uftCwCLY59AUtv24DHpy5c1w+rnBPOw175YY2H6Rbv2JPGLpJlGZGLbGd60bjOP3LfNVdrOAu7/ooUls3VnAo=,iv:AVc3I3+pCjp/GNqjFnM7RoKaWAh0ibonjaEYIXFnieQ=,tag:/T+9D90UG0oYJ9YR+f8FTg==,type:str]
                    PATRONI_REPLICATION_PASSWORD: ENC[AES256_GCM,data:qJaJmGDF/e8s2+CQRWYp+gIdOqb0+z6ig6lMnbFYgxlJUJ1da0pUiXhXkujxdwHMFLg6fpFxQsKmJ8++2JSMZttPCGo=,iv:X1udwbaEZtUFBWjqeIqHcldrUL5mMAxhQYd0q1iQrOE=,tag:YLnsbTadJW4CJbhwX8LoZw==,type:str]
                    PATRONI_admin_PASSWORD: ENC[AES256_GCM,data:xHEiAjbsRxPdfAsYtjquKG/ak6GU8Ni0qbPYlI0QTmj0bgL52q9MaxDhUopYBVQIG2Muu9lreLR4vKqYenlEihz02ws=,iv:yUd+adwZypOcuIwdkHIBhdRQihYTQrDYNiejMRdqLnY=,tag:/wPNsbSZKZelECs4dslFgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qcyqkv37ymke7amppcr2l5leerq8nhr0z7g64tw0ngw8qurkza8qxgrems
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY1pvR3BYcVg4NWR6aUMr
            UW9xeWZuSjNMRkFMNWh0UVJJYi94SHN4K3g0CllBc1duS3djeng4T0ZMZFdhZWxr
            Ny9zRVJFMVYvQUViNXNLQ3JSczJUUEUKLS0tIGhWY2xIalVrNnhoUnZIYnVPbW05
            ZHZFNzQ3Vnc5WjRKaHB6Zm83d0M4YzAKVdS0mDP7RFSW1TZivo1lr6YrJqMoQ92/
            pkqqQGdgIHqoduuAg38ksEfU5sspvUGPjXTRFxvgyYtUIdBmEVKlxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T17:39:18Z"
    mac: ENC[AES256_GCM,data:Jqpqjlq2KaTm69SrrohhaFQL/XjvZaLKCzP8mdu803Xq0XeY8H0Ld3HkEOVtSNqfVKGDMrZHgT7WluMZlOJ4Pmw8jfBtUa3fEQ8PrxYVtKOTfG5VeIOjeT56KizstLOobj5+qw6v/Y9Fm2EcliJba5GEyoIJoYvYcfisNZNIqd0=,iv:2sUGE6OtpwmAKS58ibqM0auKQyD2nKZFj/CHz4Yn5aI=,tag:WefG8/VsQbOr/qgitLnI7g==,type:str]
    pgp: []
    encrypted_regex: (^(.*[Pp]ass.*)$)|(^(data|stringData)$)|(^(.*[Tt]oken.*)$)|(^(.*[Kk]ey.*)$)|(^(.*PASSWORD.*)$)
    version: 3.7.3
